//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.5
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace DingtalkApprovalApi.Entities.Dtos {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class BillTranType {

		[JsonProperty, Column(DbType = "varchar(50)", IsPrimary = true)]
		public string Guid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string BillType { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string BillTypeGuidField { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string BillTypeNameField { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string ChtName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string DetailForeignKey { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string DetailKeyField { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string DetailTable { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string EnglishName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string HeadDetailField { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string HeadTable { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string KeyField { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string Name { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string Notes { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string SavedTableName { get; set; } = string.Empty;

		[JsonProperty]
		public int? ShowIndex { get; set; }

		[JsonProperty]
		public int? ShowType { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string SubSystemGuid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(8000)")]
		public string TableRelation { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(8000)")]
		public string WhereSQL { get; set; } = string.Empty;

	}

}
