//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.5
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace DingtalkApprovalApi.Entities.Dtos {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class FieldDescription {

		[JsonProperty, Column(DbType = "varchar(50)", IsPrimary = true)]
		public string Guid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string ChtDescription { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string ChtFieldNote { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string Description { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string EnglishDescription { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string EnglishFieldNote { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string FieldName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string FieldNote { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string FieldType { get; set; } = string.Empty;

		[JsonProperty]
		public int? FType { get; set; }

		[JsonProperty]
		public bool? IsSefDef { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string Notes { get; set; } = string.Empty;

		[JsonProperty]
		public int? OrderIndex { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string TableGuid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string TableName { get; set; } = string.Empty;

	}

}
