//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.5
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace DingtalkApprovalApi.Entities.Dtos {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class MenuSubFunction {

		[JsonProperty, Column(DbType = "varchar(50)", IsPrimary = true)]
		public string Guid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string AssemblyName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string BSPluginAssembly { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string ChtName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string ClassName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string Code { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string EnglishName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string ExecuteName { get; set; } = string.Empty;

		[JsonProperty]
		public int ExecuteType { get; set; }

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string ExePath { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "image")]
		public byte[] FlowChartInfo { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string FunctionBillGuid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string FunctionCode { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(20)")]
		public string FunctionGroupCode { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string FunctionMode { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string HelpCode { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string HelpFileName { get; set; } = string.Empty;

		[JsonProperty]
		public short? ISCHECKINIT { get; set; }

		[JsonProperty]
		public short? ISG3OBJECT { get; set; }

		[JsonProperty]
		public bool? IsHidden { get; set; }

		[JsonProperty]
		public bool? IsSystem { get; set; }

		[JsonProperty]
		public bool? IsUseMiddle { get; set; }

		[JsonProperty]
		public bool IsVisible { get; set; }

		[JsonProperty]
		public int? MenuStyle { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string MenuSubSystemGuid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string MethodName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string Name { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string Notes { get; set; } = string.Empty;

		[JsonProperty]
		public int OrderIndex { get; set; }

		[JsonProperty, Column(DbType = "image")]
		public byte[] OtherInformation { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string ParentGuid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string ReportGuid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string RightModelGuid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(20)")]
		public string ShowType { get; set; } = string.Empty;

	}

}
