//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.5
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace DingtalkApprovalApi.Entities.Dtos {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class Operators {

		[JsonProperty, Column(DbType = "varchar(50)", IsPrimary = true)]
		public string Guid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "decimal(10,0)")]
		public decimal? AUDITINGLEVEL { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string BranchGuid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string CLOUDPLATCODE { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string Code { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string CustomerGuid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string departmentguid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string EmployeeGuid { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? EndDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string GroupGuid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string HelpCode { get; set; } = string.Empty;

		[JsonProperty]
		public bool IsForbidden { get; set; }

		[JsonProperty]
		public short? IsForbiddenOutPut { get; set; }

		[JsonProperty]
		public bool? IsPosUser { get; set; }

		[JsonProperty]
		public bool? IsRemotingTran { get; set; }

		[JsonProperty]
		public bool IsSystem { get; set; }

		[JsonProperty]
		public DateTime? LastLoginTime { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string LIMITPRICE { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string MAXPRICE { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? ModifyPasswordTime { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string Name { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string Notes { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string orgidentityguid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "binary(50)")]
		public byte[] Password { get; set; }

		[JsonProperty]
		public int? PasswordErrorCount { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string POSPass { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string PriceScheme { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string RightBranchGuid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string subwarehouseguid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string supplierguid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(2000)")]
		public string WareHouseGuid { get; set; } = string.Empty;

	}

}
