//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.5
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace DingtalkApprovalApi.Entities.Dtos {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class ProductPrice {

		[JsonProperty, Column(DbType = "varchar(50)", IsPrimary = true)]
		public string GUID { get; set; } = string.Empty;

		[JsonProperty]
		public bool AllowAgentImpl { get; set; }

		[JsonProperty]
		public int AnnuFee { get; set; }

		[JsonProperty]
		public DateTime? AuditingDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string AuditingGuid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string CardNote { get; set; } = string.Empty;

		[JsonProperty]
		public int Fyear { get; set; }

		[JsonProperty]
		public int ImplPrice { get; set; }

		[JsonProperty]
		public bool IsAgentPerf { get; set; }

		[JsonProperty]
		public bool IsAuditing { get; set; }

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string OperatorGuid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "decimal(18,2)")]
		public decimal Price { get; set; }

		[JsonProperty, Column(DbType = "varchar(10)")]
		public string Pricetype { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(10)")]
		public string ProdCode { get; set; } = string.Empty;

	}

}
