//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.5
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace DingtalkApprovalApi.Entities.Dtos {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class Report {

		[JsonProperty, Column(IsPrimary = true)]
		public int Report_ID { get; set; }

		[JsonProperty]
		public bool? ColorFlag { get; set; }

		[JsonProperty]
		public decimal? COLUMNCONTENTHEIGHT { get; set; }

		[JsonProperty]
		public decimal? COLUMNHEADHEIGHT { get; set; }

		[JsonProperty]
		public bool? GroupFlag { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string guid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string HEADFONT { get; set; } = string.Empty;

		[JsonProperty]
		public bool? IsNoWrap { get; set; }

		[JsonProperty]
		public bool? LandScape { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string Margins { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string Notes { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string OperatorID { get; set; } = string.Empty;

		[JsonProperty]
		public bool? PagerFlag { get; set; }

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string PagerSize { get; set; } = string.Empty;

		[JsonProperty]
		public int PaperHeight { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string PaperName { get; set; } = string.Empty;

		[JsonProperty]
		public int PaperWidth { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string PrinterName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string ReportFont { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(8000)")]
		public string ReportGroup { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string ReportID { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string ReportName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(8000)")]
		public string ReportSort { get; set; } = string.Empty;

		[JsonProperty]
		public bool? ShowNumFlag { get; set; }

		[JsonProperty]
		public bool? SubTotalFlag { get; set; }

	}

}
