//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.5
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace DingtalkApprovalApi.Entities.Dtos {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class AcrossReportDefine {

		[JsonProperty, Column(DbType = "varchar(50)", IsPrimary = true)]
		public string Guid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(200)")]
		public string AcrossDefineName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string ColTitle { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(2000)")]
		public string FilterField { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(2000)")]
		public string HiddenField { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string Notes { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string ReportCode { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(4000)")]
		public string SelectedField { get; set; } = string.Empty;

		[JsonProperty]
		public bool? ShowColumnGrandTotals { get; set; }

		[JsonProperty]
		public bool? ShowColumnHeaders { get; set; }

		[JsonProperty]
		public bool? ShowColumnTotals { get; set; }

		[JsonProperty]
		public bool? ShowDataHeaders { get; set; }

		[JsonProperty]
		public bool? ShowFilterHeaders { get; set; }

		[JsonProperty]
		public bool? ShowGrandTotalsForSingleValues { get; set; }

		[JsonProperty]
		public bool? ShowHorzLines { get; set; }

		[JsonProperty]
		public bool? ShowRowGrandTotals { get; set; }

		[JsonProperty]
		public bool? ShowRowHeaders { get; set; }

		[JsonProperty]
		public bool? ShowRowTotals { get; set; }

		[JsonProperty]
		public bool? ShowTotalsForSingleValues { get; set; }

		[JsonProperty]
		public bool? ShowVertLines { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(4000)")]
		public string StatValue { get; set; } = string.Empty;

	}

}
