//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.5
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace DingtalkApprovalApi.Entities.Dtos {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class AnalyseReportConditDefine {

		[JsonProperty, Column(DbType = "varchar(50)", IsPrimary = true)]
		public string Guid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string AnalyseReportGuid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(4000)")]
		public string BillState { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(8000)")]
		public string ConditDefine { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(8000)")]
		public string GroupCondit { get; set; } = string.Empty;

		[JsonProperty]
		public int? IsDateVisible { get; set; }

		[JsonProperty]
		public bool? IsGroupSum { get; set; }

		[JsonProperty, Column(DbType = "varchar(400)")]
		public string Notes { get; set; } = string.Empty;

		[JsonProperty]
		public bool? ShowAuditingDate { get; set; }

		[JsonProperty]
		public bool? ShowBillDate { get; set; }

		[JsonProperty]
		public bool? ShowOKDate { get; set; }

	}

}
