//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.5
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace DingtalkApprovalApi.Entities.Dtos {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class BillTemplate {

		[JsonProperty, Column(DbType = "varchar(50)", IsPrimary = true)]
		public string Guid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string AuditAssamlyName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string AuditAssemblyName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string AuditClassName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string AuditMethodName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string AuditProcAssamlyName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string AuditProcName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string BillGuid { get; set; } = string.Empty;

		[JsonProperty]
		public int? BillType { get; set; }

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string ChalkAssamlyName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string ChalkAssemblyName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string ChalkClassName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string ChalkMethodName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string ChalkProcAssamlyName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string ChalkProcName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string Code { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string DefaultNotePrintGuid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string DeleteAssamlyName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string DeleteAssemblyName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string DeleteClassName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string DeleteMethodName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string DeleteProcName { get; set; } = string.Empty;

		[JsonProperty]
		public int? Height { get; set; }

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string HelpCode { get; set; } = string.Empty;

		[JsonProperty]
		public bool? IsSystem { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string Name { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string NotePrintTypeGuid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string Notes { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string UnAuditAssamlyName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string UnAuditAssemblyName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string UnAuditClassName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string UnAuditMethodName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string UnAuditProcName { get; set; } = string.Empty;

		[JsonProperty]
		public int? Width { get; set; }

	}

}
