//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.5
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace DingtalkApprovalApi.Entities.Dtos {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class CompanyBaseInfo {

		[JsonProperty, Column(DbType = "varchar(50)", IsPrimary = true)]
		public string GUID { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(20)")]
		public string Account { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? AUDITINGDATE { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string AUDITINGGUID { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string Bank { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? BILLDATE { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string CustName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string FixeTele { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? FORBIDDENDATE { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string FORBIDDENGUID { get; set; } = string.Empty;

		[JsonProperty]
		public bool? ISAUDITING { get; set; }

		[JsonProperty]
		public bool? ISFORBIDDEN { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string OPERATORGUID { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(10)")]
		public string PostCode { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string RegiAddr { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(20)")]
		public string TlNumb { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(20)")]
		public string USCCode { get; set; } = string.Empty;

	}

}
