//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.5
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace DingtalkApprovalApi.Entities.Dtos {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class CS_Api_Log {

		[JsonProperty, Column(DbType = "varchar(50)", IsPrimary = true)]
		public string id { get; set; } = string.Empty;

		/// <summary>
		/// 创建时间
		/// </summary>
		[JsonProperty]
		public DateTime? create_time { get; set; }

		/// <summary>
		/// 钉钉更新后的数据
		/// </summary>
		[JsonProperty, Column(DbType = "text")]
		public string dd_update_data { get; set; } = string.Empty;

		/// <summary>
		/// 操作主体钉钉ID
		/// </summary>
		[JsonProperty, Column(DbType = "varchar(500)")]
		public string dd_update_id { get; set; } = string.Empty;

		/// <summary>
		/// 更新前数据库数据1
		/// </summary>
		[JsonProperty, Column(DbType = "text")]
		public string formal_data1 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "text")]
		public string formal_data2 { get; set; } = string.Empty;

		/// <summary>
		/// 失败信息
		/// </summary>
		[JsonProperty, Column(DbType = "text")]
		public string msg { get; set; } = string.Empty;

		/// <summary>
		/// 0:成功 1失败
		/// </summary>
		[JsonProperty]
		public bool? success { get; set; }

		/// <summary>
		/// 标题
		/// </summary>
		[JsonProperty, Column(DbType = "varchar(255)")]
		public string title { get; set; } = string.Empty;

		/// <summary>
		/// 1:修改人员 2：删除人员 3：新增部门 4：修改部门 5：删除部门
		/// </summary>
		[JsonProperty]
		public int? type { get; set; }

	}

}
