//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.5
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace DingtalkApprovalApi.Entities.Dtos {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class Customer {

		[JsonProperty, Column(DbType = "varchar(10)", IsPrimary = true)]
		public string CustCode { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string Account { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(20)")]
		public string Alipay { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(20)")]
		public string Area { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? AuditingDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string AuditingGUID { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string Bank { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(10)")]
		public string BusiOppo { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string BusiSource { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(20)")]
		public string City { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? ContractDate { get; set; }

		[JsonProperty]
		public DateTime? CreateDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string CredRati { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(10)")]
		public string CustClassCode { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string CustName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(1000)")]
		public string Description { get; set; } = string.Empty;

		[JsonProperty]
		public int? DirectShopNum { get; set; }

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string FixeTele { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string ImplPers { get; set; } = string.Empty;

		[JsonProperty]
		public bool? IsArt { get; set; }

		[JsonProperty]
		public bool? IsAuditing { get; set; }

		[JsonProperty]
		public bool? ISContract { get; set; }

		[JsonProperty]
		public bool? IsRefer { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string Mnemonic { get; set; } = string.Empty;

		[JsonProperty]
		public bool? MoonCake { get; set; }

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string NameUsedBefo { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(200)")]
		public string Notes { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string OldSys { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string OperatorGUID { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(20)")]
		public string PayTaxeNatu { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(10)")]
		public string PostCode { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(20)")]
		public string Province { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? ReferDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string ReferGuid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(200)")]
		public string RegiAddr { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string SalePers { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string SalesProcess { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? ServDueDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(10)")]
		public string ServPers { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string SERVPERSold { get; set; } = string.Empty;

		[JsonProperty]
		public int? StoreNum { get; set; }

		[JsonProperty, Column(DbType = "varchar(10)")]
		public string TheCustomer { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(20)")]
		public string TlNumb { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? UpdateDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(20)")]
		public string USCCode { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(20)")]
		public string WechatPay { get; set; } = string.Empty;

	}

}
