//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.5
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace DingtalkApprovalApi.Entities.Dtos {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class E_业绩明细表_10435_S1 {

		[JsonProperty]
		public int? F_ID { get; set; }

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 产品类别 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 服务人员 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 服务业绩 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 服务业绩比例 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 公司业绩 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 公司业绩比例 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 合同编号 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 开发人员 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 开发业绩 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 开发业绩比例 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 客户名称 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 年度 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 期间 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 商机人员 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 商机业绩 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 商机业绩比例 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 实施人员 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 实施业绩 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 实施业绩比例 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 收款金额 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 收款日期 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 售前顾问 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 售前顾问业绩 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 售前顾问业绩比例 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 提成发放月份 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 销售跟踪人员 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 销售跟踪业绩 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 销售跟踪业绩比例 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 业绩扣除金额 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 业绩总计 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 业务类别编号 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 原ERP类实施服务人员 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 原ERP类实施服务人员业绩 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 原ERP类实施服务人员业绩比例 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 原销售跟踪人员 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 原销售跟踪业绩 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string 原销售跟踪业绩比例 { get; set; } = string.Empty;

	}

}
