//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.5
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace DingtalkApprovalApi.Entities.Dtos {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class GLLog {

		[JsonProperty, Column(IsPrimary = true, IsIdentity = true)]
		public int FID { get; set; }

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string FComputer { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? FDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(200)")]
		public string FDescription { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string FIPAddress { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(80)")]
		public string FOptName { get; set; } = string.Empty;

		[JsonProperty]
		public int? FStatement { get; set; }

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string FUser { get; set; } = string.Empty;

	}

}
