//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.5
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace DingtalkApprovalApi.Entities.Dtos {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class PriceSet {

		[JsonProperty, Column(DbType = "varchar(50)", IsPrimary = true)]
		public string ID { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(80)")]
		public string BZ { get; set; } = string.Empty;

		[JsonProperty]
		public bool? DWJGCL { get; set; }

		[JsonProperty, Column(DbType = "decimal(18,2)")]
		public decimal? JCBL { get; set; }

		[JsonProperty, Column(DbType = "varchar(80)")]
		public string NAME { get; set; } = string.Empty;

		[JsonProperty]
		public bool? SPJGCL { get; set; }

		[JsonProperty, Column(DbType = "decimal(18,2)")]
		public decimal? ZK { get; set; }

	}

}
