//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.5
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace DingtalkApprovalApi.Entities.Dtos {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class SMSServices {

		[JsonProperty, Column(DbType = "varchar(50)", IsPrimary = true)]
		public string Guid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string AnalyseReportGuid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(200)")]
		public string ComponentName { get; set; } = string.Empty;

		[JsonProperty]
		public int? Distance { get; set; }

		[JsonProperty]
		public DateTime? FreqDayOnceTime { get; set; }

		[JsonProperty]
		public DateTime? FreqEndTime { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string FreqHappenPeriod { get; set; } = string.Empty;

		[JsonProperty]
		public int? FreqOption { get; set; }

		[JsonProperty]
		public DateTime? FreqStartTime { get; set; }

		[JsonProperty]
		public bool? IsSendDraft { get; set; }

		[JsonProperty]
		public bool? IsSendRule { get; set; }

		[JsonProperty]
		public bool? IsStart { get; set; }

		[JsonProperty]
		public DateTime? LastBegin { get; set; }

		[JsonProperty]
		public DateTime? LastEnd { get; set; }

		[JsonProperty]
		public int? LastOption { get; set; }

		[JsonProperty]
		public int? MsgType { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string Name { get; set; } = string.Empty;

		[JsonProperty]
		public int? PeriodOption { get; set; }

		[JsonProperty]
		public int? PeriodValue { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string ResultFormat { get; set; } = string.Empty;

		[JsonProperty]
		public int? SendOption { get; set; }

		[JsonProperty]
		public int? SendValue1 { get; set; }

		[JsonProperty]
		public int? SendValue2 { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string ServiceCode { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string ServiceType { get; set; } = string.Empty;

		[JsonProperty]
		public int? SortCode { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string SubSystemGuid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(500)")]
		public string TextExpression { get; set; } = string.Empty;

	}

}
