//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.5
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace DingtalkApprovalApi.Entities.Dtos {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class t_SystemProfile {

		[JsonProperty, Column(DbType = "varchar(30)", IsPrimary = true)]
		public string FCategory { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)", IsPrimary = true)]
		public string FKey { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string BillTemplateGuid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string bz { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string czry { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? fdate { get; set; }

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string FDescription { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string FExplanation { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string FFormat { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(1)")]
		public string FLevel { get; set; } = string.Empty;

		[JsonProperty]
		public bool FReadonly { get; set; }

		[JsonProperty, Column(DbType = "decimal(8,2)")]
		public decimal? FSort { get; set; }

		[JsonProperty]
		public int? fsystem { get; set; }

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string FValue { get; set; } = string.Empty;

	}

}
