//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.5
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace G3WebApiCore.Model.ApiDtos {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class ApprovalNode {

		[JsonProperty, Column(DbType = "varchar(MAX)")]
		public string approvaltype { get; set; } = string.Empty;

		/// <summary>
		/// 审批表达模板名称，例如出差申请表、差旅费报销表等
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string BillClassName { get; set; } = string.Empty;

		/// <summary>
		/// 审批表单模板编号，系统自动生成 guid
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string BilliClassid { get; set; } = string.Empty;

		/// <summary>
		/// 审批角色名称，例如发起人、部门领导、分管领导、公司领导、财务、出纳等
		/// </summary>
		[JsonProperty]
		public int characterTypes { get; set; }

		[JsonProperty]
		public int isAndOr { get; set; }

		/// <summary>
		/// 1表示该审批单流程结束，0未结束
		/// </summary>
		[JsonProperty]
		public int IsEnd { get; set; }

		/// <summary>
		/// guid 审批节点表中主键 唯一值
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string nodeid { get; set; } = string.Empty;

		/// <summary>
		/// 审批表单序号编号规则审批表单名称全拼首字母，例如出差申请，ccsq1…N
		/// </summary>
		[JsonProperty]
		public int NodeNumber { get; set; }

		[JsonProperty, Column(DbType = "varchar(MAX)")]
		public string persons { get; set; } = string.Empty;

	}

}
