//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.5
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace G3WebApiCore.Model.ApiDtos {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class ExpeOtherDetailLOG {

		[JsonProperty, Column(DbType = "decimal(18,3)")]
		public decimal BillAmount { get; set; }

		[JsonProperty]
		public int BillCount { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string BillNo { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(10)")]
		public string FeeTypeDetail { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string MAINGUID { get; set; } = string.Empty;

	}

}
