//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.5
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace G3WebApiCore.Model.ApiDtos {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class ExpeTravDetailLOG {

		[JsonProperty, Column(DbType = "varchar(50)", IsPrimary = true)]
		public string GUID { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)", IsPrimary = true)]
		public string MAINGUID { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "decimal(18,2)")]
		public decimal AccoAmount { get; set; }

		[JsonProperty]
		public int AccoCount { get; set; }

		[JsonProperty, Column(DbType = "decimal(18,4)")]
		public decimal AlloAmount { get; set; }

		[JsonProperty]
		public int AlloDay { get; set; }

		[JsonProperty, Column(DbType = "decimal(18,4)")]
		public decimal AlloPric { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string BillNo { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "decimal(18,2)")]
		public decimal CityTraAmont { get; set; }

		[JsonProperty]
		public int CityTrafCount { get; set; }

		[JsonProperty, Column(DbType = "varchar(MAX)")]
		public string CustCode { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(MAX)")]
		public string DepaCity { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(60)")]
		public string DepaCity1 { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime DepaDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(MAX)")]
		public string DestCity { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(60)")]
		public string DestCity1 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(10)")]
		public string Detailno { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "decimal(18,2)")]
		public decimal? GasAmount { get; set; }

		[JsonProperty, Column(DbType = "decimal(18,2)")]
		public decimal? HSRAmount { get; set; }

		[JsonProperty]
		public int OffDay { get; set; }

		[JsonProperty, Column(DbType = "decimal(18,2)")]
		public decimal OtherFee { get; set; }

		[JsonProperty]
		public DateTime RetuDate { get; set; }

		[JsonProperty, Column(DbType = "decimal(18,2)")]
		public decimal? TaxAmount { get; set; }

		[JsonProperty, Column(DbType = "decimal(18,2)")]
		public decimal TotalAmount { get; set; }

		[JsonProperty, Column(DbType = "decimal(18,2)")]
		public decimal TranAmount { get; set; }

		[JsonProperty]
		public int TranCount { get; set; }

		[JsonProperty, Column(DbType = "varchar(10)")]
		public string TranMode { get; set; } = string.Empty;

		[JsonProperty]
		public int? TripNo { get; set; }

	}

}
