//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.5
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace G3WebApiCore.Model.ApiDtos {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class FilterSchemeDetail {

		[JsonProperty, Column(DbType = "varchar(50)", IsPrimary = true)]
		public string Guid { get; set; } = string.Empty;

		[JsonProperty]
		public int? DetailID { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string FieldName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(80)")]
		public string FieldValue { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string FilterSchemeGuid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(200)")]
		public string FKey { get; set; } = string.Empty;

		[JsonProperty]
		public int? FType { get; set; }

		[JsonProperty, Column(DbType = "varchar(8000)")]
		public string FValue { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(4)")]
		public string LeftPar { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(10)")]
		public string Logic { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(80)")]
		public string Oper { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(4)")]
		public string RightPar { get; set; } = string.Empty;

	}

}
