//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.5
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace G3WebApiCore.Model.ApiDtos {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class GL_Dept {

		[JsonProperty, Column(DbType = "nvarchar(50)", IsPrimary = true)]
		public string Guid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string BranchGuid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string BZ { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string FDeptBm { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string FDeptID { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(80)")]
		public string FDeptName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string FZR { get; set; } = string.Empty;

		[JsonProperty]
		public bool? IsLeaf { get; set; }

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string KM1 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string KM2 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string KM3 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string KM4 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string KM5 { get; set; } = string.Empty;

		[JsonProperty]
		public int? maxnum { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string ParentGuid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string preFix { get; set; } = string.Empty;

	}

}
