//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.5
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace G3WebApiCore.Model.ApiDtos {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class GL_Stock {

		[JsonProperty, Column(DbType = "nvarchar(50)", IsPrimary = true)]
		public string Guid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string ADDR { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string BranchGuid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string BZ { get; set; } = string.Empty;

		[JsonProperty]
		public int? Children { get; set; }

		[JsonProperty]
		public int? CountPerRow { get; set; }

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string CWID { get; set; } = string.Empty;

		[JsonProperty]
		public bool? FDeleted { get; set; }

		[JsonProperty, Column(DbType = "varchar(80)")]
		public string FEMail { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(80)")]
		public string FFTPPath { get; set; } = string.Empty;

		[JsonProperty]
		public bool? FNoSale { get; set; }

		[JsonProperty, Column(DbType = "varchar(80)")]
		public string FPath { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string FPopPass { get; set; } = string.Empty;

		[JsonProperty]
		public int? FPopPort { get; set; }

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string FPopServer { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string FPopUser { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string FZR { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string ID { get; set; } = string.Empty;

		[JsonProperty]
		public bool? IsBackStock { get; set; }

		[JsonProperty]
		public bool? IsGiftStock { get; set; }

		[JsonProperty]
		public bool? IsLeaf { get; set; }

		[JsonProperty]
		public short? IsNotLocal { get; set; }

		[JsonProperty]
		public bool? IsRetail { get; set; }

		[JsonProperty]
		public short? iswhole { get; set; }

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string KM1 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string KM2 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string KM3 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string KM4 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string KM5 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(80)")]
		public string NAME { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string ParentGuid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string StockAttribute { get; set; } = string.Empty;

	}

}
