//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.5
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace G3WebApiCore.Model.ApiDtos {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class ORDERSALES {

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string ACCOUNT { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? AUDITINGDATE { get; set; }

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string AUDITINGGUID { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string BANK { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? BillDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string BillNo { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string ContBillno { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string CustCode { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string FIXETELE { get; set; } = string.Empty;

		[JsonProperty]
		public bool? ISAUDITING { get; set; }

		[JsonProperty]
		public bool? ISREFER { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string OPERATORGUID { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(20)")]
		public string ORDERERA { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(200)")]
		public string ORDERERADDR { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(20)")]
		public string ORDERERB { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string ORDERERTEL { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? REFERDATE { get; set; }

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string REFERGUID { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(200)")]
		public string REGIADDR { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string USCCODE { get; set; } = string.Empty;

	}

}
