//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.5
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace G3WebApiCore.Model.ApiDtos {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class ORDERSALESDETAIL {

		[JsonProperty, Column(DbType = "decimal(18,2)")]
		public decimal? AMOUNT { get; set; }

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string BILLNO { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string CONTPRODGUID { get; set; } = string.Empty;

		[JsonProperty]
		public int? DETAILNO { get; set; }

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string NOTES { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "decimal(18,2)")]
		public decimal? PRICE { get; set; }

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string PRODCODE { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string PRODVERNAME { get; set; } = string.Empty;

		[JsonProperty]
		public int? SITENUM { get; set; }

	}

}
