//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.5
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace G3WebApiCore.Model.ApiDtos {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class OrganizationAbutment {

		[JsonProperty, Column(DbType = "varchar(20)")]
		public string Account { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(200)")]
		public string ADDR { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string Bank { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string Code { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string ddCode { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string Director { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string DirMobNum { get; set; } = string.Empty;

		[JsonProperty]
		public bool? Disable { get; set; }

		[JsonProperty, Column(DbType = "decimal(4,2)")]
		public decimal? Discount { get; set; }

		[JsonProperty, Column(DbType = "varchar(13)")]
		public string FDMNum { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(10)")]
		public string FinaDire { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string FinanceCode { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string FixeTele { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? Forbiddendate { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string ForbiddenGuid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string FullCode { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(500)")]
		public string FullName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string Guid { get; set; } = string.Empty;

		[JsonProperty]
		public bool? IsForbidden { get; set; }

		[JsonProperty]
		public bool? IsLeaf { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string Name { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string Notes { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(13)")]
		public string ODMNum { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(10)")]
		public string OrdeDire { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string ParentGuid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string RegiAddr { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nchar(10)")]
		public string SUBCOMMISSTYPE { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string TINumb { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string USCCode { get; set; } = string.Empty;

	}

}
