//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.5
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace G3WebApiCore.Model.ApiDtos {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class TravelReqDetail {

		[JsonProperty, Column(DbType = "varchar(50)", IsPrimary = true)]
		public string GUID { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(5)")]
		public string BearOrga { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string BillNo { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string CustCode { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string CustName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string Days { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string DepaCity { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string DepaCity1 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string DepaCity2 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string DestCity { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string DestCity1 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string DestCity2 { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? EndDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string Hours { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(5)")]
		public string IsReturn { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(20)")]
		public string OtherTranMode { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string Peers { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string PeersName { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? StartDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(5)")]
		public string TranMode { get; set; } = string.Empty;

	}

}
